### ISSUE TITLE
Scenario B random lockups into dialogue audio loop (v0.95.5)

### ISSUE THREAD

**Issue by batzradio** [Eight-Mansions/linda-cubed-again#10]
At two random points in combat late in Scenario B, I've had combat lockups during fights. In the middle of an attack sequence all action and text would pause for roughly 30-45 seconds (can't estimate fairly since this was in the middle of a stream, and I was sometimes tapping fast forward while playing this through Duckstation for Windows). Then a string of prior cutscene voices would start playing and would seem to go on for a minute or two before restarting the same string of voices.

At first I thought it was a bit of in-game unreality but when it was obvious that wasn't the case and that I was hardlocked, I reset and reloaded. I've never been able to predict when this would start, and it's happened with both player character actions initiating it.

On looking at the Scenario A major glitch issue this might be related, only different actions triggering a similar instance.

**Comment by esperknight** [comment]
Huh interesting.  So its happening randomly then?  I am looking into a scenario A hard lock on console right now but probably unrelated.... (But i can hope right?).  I'll keep this in mind and see if i get lucky :)

**Comment by esperknight** [comment]
https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-6/Linda_Cubed_Again-English-Patch-v0.95.6.zip

See if this fixes the issue.  If not could you upload a memory card save? (I'll cross my fingers this does ;_;)

**Comment by hayyelisg** [comment]
Unfortunately also encountered this for the first time just now, in rose garden, attacking an enemy.
I hope this helps you, because it is somewhat baffling to me, but through series of tests, i determined it happens every time you attack something with a basic attack in rose garden, while having the lion sword eqiupped. 
Not sure if only the lion sword causes it, but i can say on my savefile the centipede saw and unarmed attacks do not cause the game to freeze. And yes, outside battles proceed as usual.
Slot 2, last save.
[saves.zip](https://github.com/Eight-Mansions/linda-cubed-again/files/14271877/saves.zip)

**Comment by esperknight** [comment]
Thanks! That's perfect for me to figure out.  I really appreciate you taking the time to narrow it down for me :D

**Comment by batzradio** [comment]
Both times it happened to me were with the Lion Sword. 
However, the first time it was in the roof garden of the tower north of Paraside (vs. hornets), and the second time it was on the overworld vs. rabbits (East Area, between Paraside and the Tower).
Also I never ran into a similar issue in Scenario A or Scenario C (so far), but then again, I haven't bothered to use the lion sword outside of B.

**Comment by batzradio** [comment]
Another instance of this to report! (Again in Duckstation.)

Scenario C in Flora Jam, using Flame Breath against Stag Beetles caused the same issue.

File 3 was my last save before this crash.

[Linda^3 Again (Japan)_TroubleshootingC-2.zip](https://github.com/Eight-Mansions/linda-cubed-again/files/14303784/Linda.3.Again.Japan._TroubleshootingC-2.zip)

**Comment by esperknight** [comment]
https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-7/Linda_Cubed_Again-English-Patch-v0.95.7.zip

This should fix the battles I hope!

**Comment by esperknight** [comment]
Latest patch now fixes the crash with the Madame Roses and other enemies when attacking with fancy weapons.  Apparently my code was still getting clobbered..... so will no close this as done! Yay!
