### ISSUE TITLE
Game Freezes on a certain dialogue

### ISSUE THREAD

**Issue by hayyelisg** [Eight-Mansions/linda-cubed-again#11]
Inside the Spurr Valley dungeon, talking to the NPC in the camping tent and choosing the Tired dialogue option locks the game on the proceeding dialogue. Interestingly enough this happened in another "choice" dialogue. the fruit one, before i saw the patch got updated to 0.95.5.
![SCPS-10039_2024-02-09_02-03-32](https://github.com/Eight-Mansions/linda-cubed-again/assets/159496120/dde61d0f-b17b-454f-a8f2-8587c735a4fe)

**Comment by hayyelisg** [comment]
oh also, forgot the important stuff lol, playing on PC, using duckstation, no settings were touched except for the graphical enhancements.

**Comment by esperknight** [comment]
Thanks!  Yeah i probably need to space those out to make them work like for the fruits one.  Do you have a save handy?  (I think I might but I can't remember which I have for which haha).

**Comment by hayyelisg** [comment]
[savestates.zip](https://github.com/Eight-Mansions/linda-cubed-again/files/14222455/savestates.zip)
Yeah not sure if u needed a savestate or a memory card one, so i included both. The regular one is in Eterna.

**Comment by esperknight** [comment]
Give this a test.  I believe i fixed it (I didnt find the tent so I didnt test im bad hahah)

https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-6/Linda_Cubed_Again-English-Patch-v0.95.6.zip

**Comment by hayyelisg** [comment]
Yep, fixed, thank you for your hard work!

**Comment by esperknight** [comment]
Yay awesome! Thanks for testing!
