### ISSUE TITLE
Real hardware support?

### ISSUE THREAD

**Issue by DPS2004** [Eight-Mansions/linda-cubed-again#13]
Hi, I saw this on [Read Only Memo](https://www.readonlymemo.com/), and was wondering if this can be played on a real PSX that has the ability to run burned discs? The readme mentions emulators, but I just want to make sure that it will actually work before I dig up my disc drive again.

**Comment by esperknight** [comment]
Yep!! It should work fine on console!  I've only tested on xstation though.... But in theory should work fine from a disc too.
