### ISSUE TITLE
Scenario B NPC disappearing

### ISSUE THREAD

**Issue by hayyelisg** [Eight-Mansions/linda-cubed-again#14]
This bug isn't that detrimental to gameplay, mostly visual.
In scenario B, during this forced dialogue with Smilly, his right partner momentarily duplicates and appears in the wall, then all copies of him disappear. After the dialogue, you can't interact with him in any way, not even bump into him, which probably means he's completely gone, not just invisible or stuff like that. 
Fortunately, this NPC reappears once you reenter this floor, and you can interact with him normally.
On a sidenote, i recall seeing a similar glitch when talking to Elizabeth Green in Scenario A, where a sprite of a female npc suddenly appeared to the left when talking to her, but quickly disappeared. Unfortunately i didn't note that at the moment, and have overwritten the saves. But that bug, like this one wasn't very detrimental to gameplay so it's not that unfortunate.

Attached is the screenshot of the bug, and memorycard. Memorycard 2, slot 3, OzPort hotel is where the bug is located.
![image](https://github.com/Eight-Mansions/linda-cubed-again/assets/159496120/db8d26b7-d98d-46e2-8e20-0a3cae0e2f39)
[lindasavestate.zip](https://github.com/Eight-Mansions/linda-cubed-again/files/14251494/lindasavestate.zip)

**Comment by esperknight** [comment]
Thanks!  Another mentioned this before but didn't have the saves for this. This'll help a lot!

**Comment by eklomben** [comment]
I got to this part on hardware and it locked the entire game up during the dialogue.

**Comment by esperknight** [comment]
@eklomben @hayyelisg Fixed with the latest patch.  Another tested on real hardware for me so confirmed fixed on there.

https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-7/Linda_Cubed_Again-English-Patch-v0.95.7.zip
