### ISSUE TITLE
Untranslated Item

### ISSUE THREAD

**Issue by hayyelisg** [Eight-Mansions/linda-cubed-again#16]
Scenario B, Got this item in Flora Jam, Pretty sure it's supposed to be a bloodberry but don't quote me on that.
![image](https://github.com/Eight-Mansions/linda-cubed-again/assets/159496120/b6072f8c-81bc-4e31-902e-6ddb31c7aa74)

**Comment by esperknight** [comment]
Ooh nice find! I'll take a look for that one :)  (I'm guessing it's off by it's lonesome somewhere...)

**Comment by esperknight** [comment]
Fixed with latest patch! (Actually it was fixed in the previous but I forgot to comment on this hahah)
