### ISSUE TITLE
Scenario C: Game Freeze in Room

### ISSUE THREAD

**Issue by batzradio** [Eight-Mansions/linda-cubed-again#17]
This is in Annabis 1F (3 Active Teleporters/Water Bridges/White Beastman Doll Chest/Major Plot Device), when I enter through the Criranc Annabis teleporter any attempt to use any teleporter to leave the room and any attempt to use a Trek Tech freezes the game.

When I enter Annabis 1F through the teleporter network in Annabis itself (passing through the computer room) none of the freezes happen.

Running this through Duckstation.

**Comment by esperknight** [comment]
Oh thats interesting.  Do you have a save by chance?  (I can see if can test it too). Thanks!

**Comment by batzradio** [comment]
Any of the Scenario C Files (3-5) will have the well access unlocked.

[Linda^3 Again (Japan)_TroubleshootingC.zip](https://github.com/Eight-Mansions/linda-cubed-again/files/14292649/Linda.3.Again.Japan._TroubleshootingC.zip)

**Comment by batzradio** [comment]
Another issue, possibly related to https://github.com/Eight-Mansions/linda-cubed-again/issues/10 with this room, when ladybugs are available, fighting with ladybugs will randomly freeze the game and go into dialogue loop - this is especially noticeable with Ken's special moves but I had it happen on some of Linda's too (attempting to use Red Carpet a second time).

**Comment by esperknight** [comment]
Alrighty I believe this is fixed with this patch : https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-7/Linda_Cubed_Again-English-Patch-v0.95.7.zip

Let me know!  So far so good I think?

**Comment by hayyelisg** [comment]
Nope, still happens unfortunately for me

**Comment by esperknight** [comment]
Ack sorry I missed your reply!  And boo! hahah.  I'll take a look and see what's up....

**Comment by esperknight** [comment]
Fixed!  I hope for good....  Problem was my code was getting overridden.  And the fun part of testing this was I actually could get throw killing the ladybugs and Anubis sometimes.... no idea WHAT it loads that was clobbering stuff.  I thinking MAYBE it was indeed the lady bugs? And that's why certain enemies are doing it? No idea though.

@hayyelisg @batzradio give this a whirl:
https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-8/Linda_Cubed_Again-English-Patch-v0.95.8.zip

Far as I can tell it resolves the ladybug and teleporter issues at least.

**Comment by hayyelisg** [comment]
Thanks to your team's hard work, unfortunately (for testing purposes) i've already beaten the game, so i can't test out the ladybug glitch anymore, but i can confirm that teleports indeed work!

**Comment by esperknight** [comment]
@hayyelisg appreciate you testing it regardless! And I'm glad to hear you were able to beat it too :)

**Comment by esperknight** [comment]
Latest patch now fixes the crash with the Madame Roses and other enemies when attacking with fancy weapons.  Apparently my code was still getting clobbered..... so will no close this as done! Yay!
