### ISSUE TITLE
Freezes in Hospico

### ISSUE THREAD

**Issue by LoloJoestar** [Eight-Mansions/linda-cubed-again#2]
![image](https://github.com/Eight-Mansions/linda-cubed-again/assets/59673068/e47435e5-9dc0-4d50-b685-3d0704fe38d1)
Freezes right here!

**Comment by esperknight** [comment]
Already fixed :D  (Another found it yesterday).

Grab latest patch here : https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-1/Linda_Cubed_Again-English-Patch-v0.95.1.zip

**Comment by esperknight** [comment]
Also thanks!  Please keep any other issues coming!
