### ISSUE TITLE
Possible stack corruption in SetBabyLetWidth

### ISSUE THREAD

**Issue by Goatman13** [Eight-Mansions/linda-cubed-again#3]
It seems that function accidentally corrupts single word here:

https://github.com/Eight-Mansions/linda-cubed-again/blob/74c79008e668edf1b8dbf528415550f8ee34c1d2/code/linda_vwf.asm#L12
```
	addiu sp, sp, -8
	sw a0, 4(sp)
	jal SetLetter	
	sw a1, 8(sp) <---
```

Keep in mind that I'm just looking at patch code, without checking game code yet. So, if that's intended then issue can be closed.

**Comment by esperknight** [comment]
Good catch!  Yeah.... that's a not right haha.  I guess that means A1 isn't used at least :D

**Comment by esperknight** [comment]
Fixed with latest patch :)
