### ISSUE TITLE
Game freeze after Scenario A's ending cutscene

### ISSUE THREAD

**Issue by BigCoom69** [Eight-Mansions/linda-cubed-again#4]
The game freezes without fail after the final fade to black, tested on both the latest duckstation version and mednafen.

**Comment by esperknight** [comment]
Thanks!  I'll take a look into this.

**Comment by BigCoom69** [comment]
Just checked on bizhawk, it freezes there too; I wanted to make sure it wasn't an emulator configuration issue on my part.

**Comment by esperknight** [comment]
Alrighty this should fix it : https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-5/Linda_Cubed_Again-English-Patch-v0.95.5.zip

Let me know!

**Comment by BigCoom69** [comment]
Just tested and it's fixed, nice work!

**Comment by esperknight** [comment]
Awesome!  Lets hope i didn't break anything hahaha.
