### ISSUE TITLE
Game Freeze after Scenario 2 Cutscene in Paraside

### ISSUE THREAD

**Issue by TrevorZyla** [Eight-Mansions/linda-cubed-again#5]
Game freezes to black in Scenario 2 after the cutscene of Linda throwing a couch into a group of poachers plays. Cutscene happens on third floor of Junk Palace after you return from OzSat.

Version - 0.95.1
Emulator - PCSX ReArmed
Playing on a Miyoo Mini running Onion OS 4.2.3

Have not had a chance to try on a different system yet.

**Comment by esperknight** [comment]
Could you upload a memory card save of this?  Thanks!

**Comment by esperknight** [comment]
https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-4/Linda_Cubed_Again-English-Patch-v0.95.4.zip

You can try this patch to see if it fixes the freezing.  I removed graphics from various maps that weren't being used as apparently I made some of the maps too big :)  (What I get for being lazy and copy pasting the graphics hahah)

**Comment by TrevorZyla** [comment]
[Linda-English.zip](https://github.com/Eight-Mansions/linda-cubed-again/files/14155297/Linda-English.zip)

Hey there, I download the newest version of the patch, and the issue in Scenario 2, as well as the end credits issue in Scenario 1 still persists. There's a link to my save file, the save in Slot A is right before the end of Scenario 1, you just need to pilot the Ark; second save file is at Hospico, you just need to walk to Paraside and go to Floor 3 of the Junk Palace to (possibly) see the issue I am having. 

I'm gonna try with a different emulator later tonight, could be I'm just playing the game the most cursed way possible, hahaha.

Thank you and the team for all the amazing work! Been wanting to play this game for years and I'm so happy that I can finally play it! :)

**Comment by esperknight** [comment]
I was hoping hahahaha.  I figured though it may not.  And thanks!  I'll look into it with your saves.

**Comment by esperknight** [comment]
Alrighty so I tested Scenario B on Duckstation and it's good to go.  So yeah it may be an emulator issue indeed....  Hopefully you can use a different core on Miyoo Mini (I don't have one myself, instead i have the Abernic RG35XX).

Scenario A i know what the issue is... now to figure out how to fix it...

**Comment by esperknight** [comment]
Fixed the Scenario A issue : https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-5/Linda_Cubed_Again-English-Patch-v0.95.5.zip

So far it seems to work :)  (Let's hope I didn't break anything else...)

**Comment by batzradio** [comment]
For anyone else that was having the Scenario B freeze after cutscene issue in emulators (at least in Duckstation), I found a possible cause/solution. 

I had Read and Seek Speedup at 2x, but the game seemed to be disagreeable with those settings. As soon as I set them to Normal, it went through fine.

**Comment by esperknight** [comment]
Ooh interesting.  Youd think the speed up would help but I will say Linda is finicky with emulators.  Some habe trouble with how Linda is displaying graphics.

**Comment by EdoCrabo** [comment]
same happens on the eboot,pbp version on PSP/VITA sadly

**Comment by esperknight** [comment]
Try this version to see if that fixes your issue @EdoCrabo 

https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-6/Linda_Cubed_Again-English-Patch-v0.95.6.zip

I'm hoping it resolves all these cutscene issues................
