### ISSUE TITLE
Major glitch in first FMV cutscene in Scenario A

### ISSUE THREAD

**Issue by Enecororo** [Eight-Mansions/linda-cubed-again#6]
Playing it on Xstation and on standard difficulty if that matters. But I said yes when asked if I needed catching up and the cutscene stuttered before freezing visually, I decided to wait for the cutscene to end, but instead it felt like it started playing the audio for all the other cutscenes.

If this has been fixed since then, my apologies only just realized that there's been a few updates since I grabbed my version, but I'll be posting this anyway in case anyone finds out that it still applies to the current version (Me included since I'm grabbing the latest version of the patch right now)

**Comment by esperknight** [comment]
Sounds great to post it here in as you said.  That way others will see it. And yep its been fixed as of v9.5.2 (or should be....).  I tested it myself on xstation so should be all good to go :)

**Comment by esperknight** [comment]
Just realized if I mark it closed this won't show up so I'll leave it open so others can find it just in case.

**Comment by Enecororo** [comment]
Yeah I found out after I posted this that it was indeed fixed. good to know you guys responded to it in pretty good time

Only barely related but also noticed a line of NPC dialogue in the first town that was awkwardly worded, but I didn't check to see if that was changed

**Comment by esperknight** [comment]
For the dialogue feel free to post it here.  Also anything that looks odd format wise too I can try to fix.

And I try to be quck hahaha.  Linda is such a large game its hard to catch everything :)  (As some things I fixed then re-broke......)

**Comment by Enecororo** [comment]
I'll have to see if I can find the dialogue again next time I boot it up. Just quit for the night myself. Hopefully its not one that changes after the season changes/after the prologue

**Comment by xorphplex** [comment]
Hi - I'm on Xstation too on v0.95.4 and the glitch still seems to be happening. It's improved from pre-fix but still there on mine - on one play it just froze on one scene a few seconds too long (so was almost not noticeable), but the second time I tried it did the full glitching out with visual corruption like before again.

It's happening roughly in the middle of the FMV, and then seems to fix itself a few seconds before the scene ends.

**Comment by esperknight** [comment]
@xorphplex Try this one if you can.  We tweaked another line to hopefully allow it to be displayed faster.  Thanks!

[Uploading linda-psx-patcher_02_04_2024.zip…](Linda FMV Fix)

**Comment by esperknight** [comment]
(https://drive.google.com/file/d/1N9nyE9RCDy9Tbyv0RzJo6wy-ehPV2X8J/view?usp=sharing)

**Comment by xorphplex** [comment]
Alright, that did it! (And it looks all good in 0.95.5 too). Nice work, thanks!

**Comment by esperknight** [comment]
Thanks!  I forgot to mention 95.5 is this too now haha with a bit more :)

**Comment by CrabLord1999** [comment]
I get a Black screen after a cutscene in Scenario B :( Im on 95.5

**Comment by esperknight** [comment]
@CrabLord1999 which FMV?  Also could you upload a memory card for it and how to access it?  Also on console or emulator?

**Comment by CrabLord1999** [comment]
@esperknight  the FMV in Paraside when you first see Linda after talking to the proxy rangers. Im playing on the Eboop.pbp version for PSP/VITA. I can upload the file later today when Im at home

**Comment by froggymachine** [comment]
Hey all,
I’m getting the glitch where the game locks up after the Santa fight. I’m on the latest version and I’ve tried maybe 5 or 6 times with various settings. For some reason the latest time it crashed it left up a symbol in the top left. Screenshot attached.
Playing on Vita Adrenaline with eboot.
![IMG_0957](https://github.com/Eight-Mansions/linda-cubed-again/assets/159493698/b19de267-3b70-4eb2-9e2f-6271788e4e34)

**Comment by esperknight** [comment]
@froggymachine working that one now!  It's been  a fun one... I think I may know exactly whats causing it though... so lets see....

**Comment by esperknight** [comment]
@froggymachine Fixed! (It better be ;_; hahaha).  

Use this patch : https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-6/Linda_Cubed_Again-English-Patch-v0.95.6.zip

@CrabLord1999 Give this a try too. I suspect its the same issue as with Scenario A (I'm hoping....)

**Comment by froggymachine** [comment]
@esperknight That fixed it perfectly, thank you so much! I was able to continue after the fight and proceed to the ending without issues.
Thanks for the quick fix, great work on this in general! :)

**Comment by esperknight** [comment]
Yay!  Really glad to hear you were able to beat scenario a with no issue after @froggymachine!
