### ISSUE TITLE
POPStarter PS2 Emulator Cutscenes Incredibly slow

### ISSUE THREAD

**Issue by ApolloEM** [Eight-Mansions/linda-cubed-again#7]
When the patch came out I was really excited to play it on my ps2, however it seems that the cutscenes have incredible slowdown, it's not even frames per second, and more like 2-3 seconds per frame and it makes it almost impossible to progress past the first set of cutscenes. I'm not quite sure if anything can be done about this, since it's most likely an emulator quirk but I thought it would be worth a shot to ask. Thank you in advance!

**Comment by esperknight** [comment]
Hmm yeah I don't think I can help with that.  From what others have told me it'd be best to pay this off disc or from the hard drive as it seems popstarter isn't very compatible with many games.  Everything works well on ps1, psp, vita, and ps3 so not sure I can do much to help with popstarter...
