### ISSUE TITLE
How to drag ISO onto BAT on Mac?

### ISSUE THREAD

**Issue by SteakSauceDrip** [Eight-Mansions/linda-cubed-again#8]
Hi, I’m pretty new to this and I couldn’t figure out how to follow the instructions on Mac since dragging and dropping didn’t work.
![Image](https://github.com/Eight-Mansions/linda-cubed-again/assets/159075419/bcb25435-188d-4207-a15b-00fdc8a0c285)

**Comment by krisu5** [comment]
BAT files only work on Windows.

Maybe devs / other people can be more helpful because I'm not currently using Mac, but try [MultiPatch](https://www.romhacking.net/utilities/746) or google for [other mac patching solutions](https://www.google.com/search?q=xdelta%20mac).

**Comment by esperknight** [comment]
Thanks @krisu5!  Just as you said :)

**Comment by MediaMaquina** [comment]
@SteakSauceDrip Try this https://kotcrab.github.io/xdelta-wasm/
