### ISSUE TITLE
Update Patch While Keeping Saves?

### ISSUE THREAD

**Issue by friendbow** [Eight-Mansions/linda-cubed-again#9]
Hello!

I encountered the black screen/softlock glitch at the credits of Scenario A, and I see that you've just released a patch that fixes it. How can I change to the updated patch while keeping my current data? I'm not very knowledgeable about this and I don't want to accidentally delete my saves.

Thank you!

**Comment by esperknight** [comment]
As long as your using a memory card save and not a save state then you can just apply the patch to the original iso and continue to use your memory card saves no problem with it

**Comment by friendbow** [comment]
That's great to hear, thank you so much!
